### PR TITLE
Adds blt addon command

### PR DESCRIPTION
**Pull request by shelane**

### CODE REVIEW

**Comment by achekulaev** [comment]
So I guess you need to somehow install it first?

**Comment by shelane** [comment]
Install blt, yes. It assumes you already have a blt project. This is just for running blt commands.

**Comment by achekulaev** [comment]
Could you include steps to install blt into your project in README? Because I guarantee that people will install this addon and complain that it does not work,

**Comment by shelane** [comment]
Sure thing. I will do that.

**Comment by shelane** [comment]
I added a link to my blog post and linked again to the BLT docs.

**Comment by opdavies** [comment]
Not sure what's considered best practice, but would it be better to use `$PROJECT_ROOT` rather than hard-coding `/var/www`?

**Comment by achekulaev** [comment]
Inside container ${PROJECT_ROOT} is always /var/www so there is no real difference.

**Pull request merged**
