### PR TITLE
Andock

### PR DESCRIPTION
**Pull request by christianwiedemann**
Hi Docksal Team,

I provided a pull request some months ago with andock-ci (acp). 

I renamed the project to Andock and changed the scope of the project. 

With Andock it is dead simple to get Docksal environments on a server for production and testing. 
Andock automates the build, environment creation, Certificate generation, File permission, Server setup, Container generation, different configuration for each environment, SSH access, Drush aliases, etc. 

I released the first version some days ago and completed the documentation
(https://andock.readthedocs.io/en/latest/)

I know there are a lot of tools out there which do docker deployments - but I think there is no simple one. And I think there is nothing more simple than the same tool I use on my local dev machine. 
... and docker-compose based hosting is good enough for a wide range of projects (I would say ).

So hope you can have a look at it accept the PR. And of course I am quite interested what you think about?

### CODE REVIEW

**Comment by acondura** [comment]
Hello Christian, I've just finished reading the Andock documentation and I could really use this for a current client for which I've created a 'sandbox' bash command to automate dev envs for different colleagues using different code branches. I'm glad to see you included support for LetsEncrypt as well, which I had added to my 'sandbox' command too but I see you've got a more robust implementation.

One thing I'm curious about. I'm currently using nip.io for dev envs, including LetsEncrypt. Can andock work with nip.io (especially since they make it easy for LetsEncrypt)?

**Comment by achekulaev** [comment]
Sounds exciting Chris

**Comment by christianwiedemann** [comment]
Hi @acondura yes Andock works with nip.io. 

Use for example `"{{ branch }}.138-68-112-178.nip.io"` or `"{{ branch }}.project.138-68-112-178.nip.io"` as vritual host pattern in `andock.yml` 
```
virtual_hosts:
  default:
    virtual_host: "{{ branch }}.138-68-112-178.nip.io"
    container: web
```
If you have any other question you can ping me in gitter (https://gitter.im/andock/community-support?source=orgpage)

(Will note nip.io in my docs. It's perfect for the 15 min setup. Thanks!)

**Comment by acondura** [comment]
I'm not sure what's going on with nip.io because they currently ask for username and password, they seem to have added basic authentication so, I'm not sure what's going on with their service. Maybe they had too many requests or something.

Another free wildcard DNS service with SSL support is https://sslip.io and they offer some white label option too.

**Pull request merged**
